### PR TITLE
Remove extra function call

### PR DESCRIPTION
**Pull request by just-boris**
There is no need to call require again since the core module do it itself here: https://github.com/jrburke/requirejs/blob/master/require.js#L1074

I've tested on `demo` and `demo-build` showcases and want to use it in my project.

### CODE REVIEW

**Comment by kumarharsh** [comment]
Thanks @just-boris. I'll have a look and merge it probably over the weekend

**Comment by just-boris** [comment]
@kumarharsh any news?

**Comment by kumarharsh** [comment]
@just-boris am on a vacation for a few more days... will take a look when I return.

Regards
Harsh

**Comment by kumarharsh** [comment]
seems like that line was there from the first commit...

**Pull request merged**
